name: Build Docker Images
on: [push, repository_dispatch]

jobs:
  build:
    name: Docker-Remotely
    runs-on: ubuntu-latest
    steps:
      - id: remotely
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: lucent-sea/Remotely
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexdelifer/docker-remotely
          dockerfile: Dockerfile
          build_args: VERSION=${{ steps.remotely.outputs.release }}
          tags: latest, ${{ steps.remotely.outputs.release }}
