name: Build Docker Images
on: [push, repository_dispatch]

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - id: remotely
        name: Get Latest Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: lucent-sea/Remotely
      - uses: actions/checkout@v2
        name: Checkout Repo
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
      - uses: docker/login-action@v1
        name: DockerHub Login 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        name: Build and Push
        with:
          push: true
          build-args: VERSION=${{ steps.remotely.outputs.release }}
          tags: delifer/remotely:latest, delifer/remotely:${{ steps.remotely.outputs.release }}
