name: Build Docker Images
on: [push, repository_dispatch]

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - id: remotely
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: lucent-sea/Remotely
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.remotely.outputs.release }}
          tags: delifer/remotely:latest, delifer/remotely:${{ steps.remotely.outputs.release }}
