name: Build Docker Images
on:
  push:
    paths:
      - 'release_versions/**'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - id: remotely
        name: Get Latest Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: lucent-sea/Remotely

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub Login 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: VERSION=${{ steps.remotely.outputs.release }}
          tags: allram/remotely:latest,allram/remotely:${{ steps.remotely.outputs.release }}
